stages:
  - build
  - test
  - deploy
  - cleanup

build:
  stage: build
  script:
    - docker build -t drh/ci-node --file ci/Dockerfile .
  only:
    - develop
    - master

test:
  stage: test
  script:
    - docker run --rm drh/ci-node npm run test
  only:
    - develop
    - master

deploy:
  stage: deploy
  script:
    - docker run --rm -v $(pwd)/dist:/dist drh/ci-node npm run build
    - docker run --rm -v $(pwd)/dist/:/deploy/dist --env DEPLOY_PATH=stage drh/deploy
  only:
    - master

cleanup:
  stage: cleanup
  script:
    - echo "Cleaning unused images."
    - docker rmi -f $(docker images -f "dangling=true" -q)
    - docker rmi -f drh/ci-node
  when: always