stages:
  - env
  - test
  - build
  - deploy

build_env:
  stage: env
  script:
    - docker build -t drh/ci-node --file ci/Dockerfile .
  only:
    - develop

test:
  stage: test
  script:
    - docker run --rm drh/ci-node
  only:
    - develop

build:
  stage: build
  script:
    - ls
    - echo "building..."
  only:
    - master

deploy:
  stage: deploy
  script:
    - ls
    - echo "deploying..."
  only:
    - master