stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker build -t drh/ci-node --file ci/Dockerfile .
  only:
    - develop
    - master

test:
  stage: test
  script:
    - docker run --rm drh/ci-node npm run test
  only:
    - develop
    - master

deploy:
  stage: deploy
  script:
    - docker run --rm -v $(pwd)/dist:/dist drh/ci-node npm run build
    - docker run --rm -v $(pwd)/dist/:/deploy/dist --env DEPLOY_PATH=stage drh/deploy
  only:
    - master