stages:
  - env
  - test
  - build
  - deploy

build_env:
  stage: env
  script:
    - docker build -t drh/ci-node --file ci/Dockerfile .
  only:
    - develop

test:
  stage: test
  script:
    - docker run --rm drh/ci-node npm run test
  only:
    - develop

build:
  stage: build
  script:
    - docker run --rm drh/ci-node v $(pwd)/dist:/dist npm run build
  only:
    - master

deploy:
  stage: deploy
  script:
    - docker run --rm -it -v $(pwd)/dist/:/deploy/dist --env DEPLOY_PATH=stage drh/deploy
  only:
    - master